CR2 et CR3
suricats/lab-bot pull request #2
Opened 2016-11-01 14:20 UTC by kostrik

2016-11-01 15:40 UTC, migibert requested changes

2016-11-01 15:40 UTC, migibert commented on docs/token.txt
> +Le Slack Bot Token est : xoxb - 91352476245 - IRGv4OMFC2fn92Ehf0zDzXzX
A ne pas faire figurer ici, il est public!
1 - supprimez cette information du repository
2 - désactivez ce token côté slack
3 - générez en un nouveau et ajoutez le à l'environnement cible

2016-11-01 15:40 UTC, migibert commented on docs/token.txt
> +(retirer les espaces, Slack scanne les projets Github et r�p�re ses tokens)
attention à l'encodage

2016-11-01 15:40 UTC, migibert commented on .travis.yml
> +- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
A quoi sert ce "mvn install" ?

2016-11-01 15:40 UTC, migibert commented on src/sprint1/main/MainBot.java
>  			throw new Error("Add LAB_BOT with the token to your environment variables. (see in resources/init.sh)");
Ce message n'est plus vrai (il n'y a plus de init.sh)

2016-11-01 15:40 UTC, migibert commented on .travis.yml
> +- sshpass -p "$password" ssh -o StrictHostKeyChecking=no travis@$IP java -jar *.jar
Attention, par défaut votre application est disponible sur le port 8080, hors ce n'est pas le port qui est ouvert sur votre environnement.
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-change-the-http-port

2016-11-05 15:33 UTC, JulienMrgrd commented
Pull Request du Sprint 3 et 4.

2016-11-17 13:23 UTC, closed without merging